language: cpp
sudo: false

branches:
  except:
    - gh-pages

addons:
  apt_packages:
      - libgmp3-dev
      - parallel
      - valgrind
env:
  - MAKEFLAG="CHECK=1"
  - MAKEFLAG="CHECK=0"



install:
  - git clone --depth=2 https://github.com/gap-system/gap.git gap
  - pwd
  - ( cd gap && ./configure --with-gmp=system && make )
  - pwd
  - ( ./configure gap && make )
  - ls gap/pkg
  - ls
  - echo ln -s $(pwd) gap/pkg/ferret
  - ln -s $(pwd) gap/pkg/ferret
  - cat ferret.vars

script:
  - scripts/quick_test.sh ${MAKEFLAG}
