language: cpp
sudo: false

branches:
  except:
    - gh-pages

addons:
  apt:
    packages:
      libgmp3-dev
      parallel
      valgrind
env:
  - MAKEFLAG="CHECK=1"
  - MAKEFLAG="CHECK=0"



install:
  - git clone --depth=2 https://github.com/gap-system/gap.git gap
  - pwd
  - cd gap && ./configure --with-gmp=system && make
  - pwd
  - ./configure /opt/gap && make
  - mkdir gap-root && mkdir gap-root/pkg && ln -s $(pwd) gap-root/pkg/ferret
  - echo 'export GAPEXEC="$GAPEXEC -l '$(pwd)'/gap-root;"' >> ferret.vars
  - cat ferret.vars

script:
  - scripts/quick_test.sh ${MAKEFLAG}
