language: cpp
sudo: required
dist: precise

branches:
  except:
    - gh-pages

addons:
  apt_packages:
      - libgmp3-dev
      - parallel
      - valgrind
env:
  - MAKEFLAG="CHECK=1"
  - MAKEFLAG="CHECK=0"



install:
  - gcc -v
  - g++ -v
  - git clone --depth=2 https://github.com/gap-system/gap.git gap
  - pwd
  - ( cd gap && ./configure --with-gmp=system && make && make bootstrap-pkg-minimal)
  - ( cd gap/pkg && git clone --depth=2 https://github.com/gap-packages/io && cd io && ./autogen.sh && ./configure && make )
  - ( cd gap/pkg && wget http://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/atlasrep1r5p0.tar.bz2 && tar -xf atlasrep1r5p0.tar.bz2 )
  - pwd
  - ( ./configure gap && make )
  - pwd
  - ls
  - ls gap
  - ls gap/pkg
  - echo ln -s $(pwd) gap/pkg/ferret
  - ln -s $(pwd) gap/pkg/ferret
  - cat ferret.vars

script:
  - scripts/quick_test.sh ${MAKEFLAG}
