name: ferret
version: 0.6.0
date: 09/07/2016
description: Backtrack Search in Permutation Groups

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://gap-packages.github.io/ferret/
readme: http://gap-packages.github.io/ferret/README
packageinfo: http://gap-packages.github.io/ferret/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/ferret/releases/download/v0.6.0/ferret-0.6.0.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
