name: ferret
version: 0.3.1
date: 09/10/2014
description: Search in finite permutation groups

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://bitbucket.org/ChrisJefferson/ferret/
readme: https://bitbucket.org/ChrisJefferson/ferret/README
packageinfo: https://bitbucket.org/ChrisJefferson/ferret/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://bitbucket.org/ChrisJefferson/ferret/ferret-0.3.1.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
