name: ferret
version: 0.5.1
date: 12/01/2015
description: Search in finite permutation groups

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://gap-system.github.io/ferret/
readme: http://gap-system.github.io/ferret/README
packageinfo: http://gap-system.github.io/ferret/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-system/ferret/releases/download/v0.5.1/ferret-0.5.1.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
